Repository DaniloDiasLTDA/study-plan-calculator-qt6, pull requests merged in 2025-04, with the labels that each got.

#1 chore: project name
  README.md
Labels: enhancement

#2 docs: add study plan
  docs/study-plan.md
Labels: documentation

#6 Feature/study csv module
  .gitignore
  csv_study/.todo.md
  csv_study/estudo_csv.py
Labels: study
